const ADD_TODO_LOADING = "ADD_TODO_LOADING";
const ADD_TODO_SUCESS = "ADD_TODO_SUCESS";
const ADD_TODO_ERROR = "ADD_TODO_ERROR";

const GET_TODO_LOADING = "GET_TODO_LOADING";
const GET_TODO_SUCESS = "GET_TODO_SUCESS";
const GET_TODO_ERROR = "GET_TODO_ERROR";

const REMOVE_TODO_LOADING = "REMOVE_TODO_LOADING";
const REMOVE_TODO_SUCESS = "REMOVE_TODO_SUCESS";
const REMOVE_TODO_ERROR = "REMOVE_TODO_ERROR";

const TOGGLE_TODO_LOADING = "TOGGLE_TODO_LOADING";
const TOGGLE_TODO_SUCESS = "TOGGLE_TODO_SUCESS";
const TOGGLE_TODO_ERROR = "TOGGLE_TODO_ERROR";

export {
  ADD_TODO_LOADING,
  ADD_TODO_SUCESS,
  ADD_TODO_ERROR,
  GET_TODO_LOADING,
  GET_TODO_SUCESS,
  GET_TODO_ERROR,
  REMOVE_TODO_LOADING,
  REMOVE_TODO_SUCESS,
  REMOVE_TODO_ERROR,
  TOGGLE_TODO_LOADING,
  TOGGLE_TODO_SUCESS,
  TOGGLE_TODO_ERROR,
};
